# Generated by Django 4.2.2 on 2023-09-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recurring", models.BooleanField()),
                ("day", models.DateField()),
                ("time", models.DateTimeField()),
                ("title", models.TextField()),
                ("account", models.TextField()),
                ("host", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("day", models.DateField()),
                ("roles", models.TextField()),
            ],
        ),
    ]
