# Generated by Django 4.2.2 on 2023-09-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_events_streamer_alter_events_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="end_time",
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name="events",
            name="start_time",
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="roles",
            field=models.CharField(
                choices=[
                    ("Host", "Host"),
                    ("Moderator", "Moderator"),
                    ("Facilitator", "Facilitator"),
                    ("Streamer", "Streamer"),
                    ("Broadcaster", "Broadcaster"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
