# Generated by Django 4.2.5 on 2023-09-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_events_end_time_alter_events_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="email",
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="events",
            name="account",
            field=models.CharField(
                choices=[
                    ("com", "com"),
                    ("com2", "com2"),
                    ("com3", "com3"),
                    ("com4", "com4"),
                    ("ch", "ch"),
                    ("web ch", "web ch"),
                    ("n/a", "n/a"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
