# Generated by Django 4.2.2 on 2023-09-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_events_end_time_alter_events_start_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_slot", models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="day",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="availabilities",
            field=models.ManyToManyField(to="myapp.availability"),
        ),
    ]
