# Generated by Django 4.2.2 on 2023-09-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_availability_remove_volunteer_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.events"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="availabilities",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="email",
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name="Availability",
        ),
        migrations.AddField(
            model_name="registration",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.volunteer"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="registrations",
            field=models.ManyToManyField(
                through="myapp.Registration", to="myapp.volunteer"
            ),
        ),
    ]
