# Generated by Django 4.2.5 on 2023-09-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_volunteer_email_alter_events_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='day',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='events',
            field=models.ManyToManyField(to='myapp.events'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.volunteer')),
            ],
        ),
    ]
