# Generated by Django 4.2.5 on 2023-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_remove_volunteer_day_volunteer_events_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="type_of_event",
            field=models.CharField(
                choices=[("social", "social"), ("educational", "educational")],
                default=None,
                max_length=255,
            ),
        ),
    ]
