# Generated by Django 4.2.2 on 2023-09-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_registration_remove_volunteer_availabilities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="registrations",
        ),
        migrations.AddField(
            model_name="volunteer",
            name="events",
            field=models.ManyToManyField(to="myapp.events"),
        ),
    ]
