# Generated by Django 4.2.5 on 2023-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_events_type_of_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="type_of_event",
            field=models.CharField(
                choices=[
                    ("", "Select Type"),
                    ("Social", "Social"),
                    ("Educational", "Educational"),
                ],
                default=None,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="roles",
            field=models.CharField(
                choices=[
                    ("", "Select Role"),
                    ("Host", "Host"),
                    ("Moderator", "Moderator"),
                    ("Facilitator", "Facilitator"),
                    ("Streamer", "Streamer"),
                    ("Broadcaster", "Broadcaster"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
