# Generated by Django 4.2.5 on 2023-09-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_events_type_of_event_alter_volunteer_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="account",
            field=models.CharField(
                choices=[
                    ("", "Select Account"),
                    ("com", "com"),
                    ("com2", "com2"),
                    ("com3", "com3"),
                    ("com4", "com4"),
                    ("ch", "ch"),
                    ("web ch", "web ch"),
                    ("n/a", "n/a"),
                ],
                default=None,
                max_length=255,
            ),
        ),
    ]
